name: Setup Dagger Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dagger:
    name: Setup Dagger Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: false

      - name: Setup Dagger Pipeline
        uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run pipeline.go
          version: "0.14.0"

      - name: Move Model Artifact to Model Folder
        run: |
              mkdir -p model
              mv output/lead_model_lr.pkl model/model.pkl

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: model/model.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
